// Standardized options for restaurants and food items

export const RESTAURANT_TYPES = [
  "Fast Food",
  "Fast Casual",
  "Casual Dining",
  "Fine Dining",
  "Cafe / Coffee Shop",
  "Bar / Pub / Tavern",
  "Food Truck / Cart",
  "Buffet",
  "Diner",
];

export const CUISINE_TYPES = [
  // The Americas
  "American (New)",
  "American (Traditional)",
  "BBQ",
  "Cajun & Creole",
  "Caribbean",
  "Latin American",
  "Mexican",
  "South American",

  // European
  "British",
  "Eastern European",
  "French",
  "German",
  "Greek",
  "Italian",
  "Mediterranean",
  "Portuguese",
  "Spanish",

  // Asian
  "Asian",
  "Chinese",
  "Filipino",
  "Indian",
  "Japanese",
  "Korean",
  "Thai",
  "Vietnamese",

  // Middle Eastern & African
  "African",
  "Middle Eastern",
  "Turkish",

  // Global & Fusion
  "Fusion",
  "Gastropub",
  "Seafood",
  "Steakhouse",
  "Vegan / Vegetarian",
];

export const AMBIANCE_OPTIONS = [
  "Family-Friendly",
  "Romantic",
  "Casual",
  "Lively / Noisy",
  "Quiet / Intimate",
  "Trendy / Modern",
  "Upscale / Formal",
  "Cozy",
  "Good for Groups",
  "Outdoor Seating",
];

export const FOOD_CATEGORIES = [
  "Appetizers & Starters",
  "Soups & Salads",
  "Handhelds",
  "Mains / Entrées",
  "Pizza & Flatbreads",
  "Pasta",
  "Sides",
  "Desserts",
  "Drinks (Non-Alcoholic)",
  "Drinks (Alcoholic)",
  "Breakfast & Brunch",
];

export const FOOD_TYPES = {
  "Appetizers & Starters": [
    "Wings",
    "Nachos",
    "Calamari",
    "Bruschetta",
    "Mozzarella Sticks",
    "Spinach Dip",
    "Sliders",
    "Quesadillas",
    "Stuffed Mushrooms",
    "Shrimp Cocktail",
  ],
  "Soups & Salads": [
    "Caesar Salad",
    "House Salad",
    "Greek Salad",
    "Chicken Soup",
    "Tomato Soup",
    "Clam Chowder",
    "French Onion Soup",
    "Minestrone",
    "Cobb Salad",
    "Caprese Salad",
  ],
  "Handhelds": [
    "Burger",
    "Tacos",
    "Burrito",
    "Hot Dog",
    "Sandwich",
    "Wrap",
    "Panini",
    "Sub",
    "Club Sandwich",
    "Grilled Cheese",
  ],
  "Mains / Entrées": [
    "Steak",
    "Fried Rice",
    "Curry",
    "Grilled Chicken",
    "Fish & Chips",
    "Lobster",
    "Pork Chops",
    "Lamb",
    "Salmon",
    "Ribs",
  ],
  "Pizza & Flatbreads": ["Pizza", "Flatbread", "Calzone", "Stromboli"],
  "Pasta": [
    "Spaghetti",
    "Fettuccine",
    "Penne",
    "Lasagna",
    "Ravioli",
    "Gnocchi",
    "Linguine",
    "Carbonara",
  ],
  "Sides": [
    "Fries",
    "Onion Rings",
    "Coleslaw",
    "Garlic Bread",
    "Rice",
    "Mashed Potatoes",
    "Steamed Vegetables",
    "Mac & Cheese",
  ],
  "Desserts": [
    "Churro",
    "Cake",
    "Ice Cream",
    "Cheesecake",
    "Tiramisu",
    "Brownie",
    "Apple Pie",
    "Crème Brûlée",
  ],
  "Drinks (Non-Alcoholic)": [
    "Soda",
    "Juice",
    "Coffee",
    "Tea",
    "Smoothie",
    "Milkshake",
    "Lemonade",
    "Water",
  ],
  "Drinks (Alcoholic)": [
    "Beer",
    "Wine",
    "Cocktail",
    "Whiskey",
    "Vodka",
    "Rum",
    "Tequila",
    "Margarita",
  ],
  "Breakfast & Brunch": [
    "Pancakes",
    "Waffles",
    "French Toast",
    "Eggs Benedict",
    "Omelet",
    "Breakfast Burrito",
    "Bagel",
    "Avocado Toast",
  ],
};

export const FOOD_SUBTYPES = {
  "Burger": [
    "Cheese Burger",
    "Bacon Burger",
    "Veggie Burger",
    "Smash Burger",
    "BBQ Burger",
    "Mushroom Swiss Burger",
    "Turkey Burger",
    "Black Bean Burger",
  ],
  "Tacos": [
    "Beef",
    "Chicken",
    "Fish",
    "Pork (Al Pastor)",
    "Birria",
    "Carnitas",
    "Shrimp",
    "Vegetarian",
  ],
  "Burrito": [
    "Beef",
    "Chicken",
    "Bean & Cheese",
    "Carnitas",
    "California",
    "Breakfast",
    "Veggie",
    "Fish",
  ],
  "Hot Dog": [
    "Classic",
    "Chili Cheese",
    "Chicago Style",
    "New York Style",
    "Corn Dog",
    "Specialty",
  ],
  "Sandwich": [
    "Club",
    "BLT",
    "Philly Cheesesteak",
    "Meatball Sub",
    "Italian",
    "Reuben",
    "Grilled Chicken",
    "Tuna Melt",
  ],
  "Steak": [
    "Filet Mignon",
    "Ribeye",
    "Sirloin",
    "T-Bone",
    "New York Strip",
    "Porterhouse",
    "Flank Steak",
  ],
  "Fried Rice": [
    "Chicken",
    "Beef",
    "Shrimp",
    "Vegetable",
    "Pork",
    "Combination",
  ],
  "Curry": [
    "Red Curry",
    "Green Curry",
    "Panang Curry",
    "Yellow Curry",
    "Thai Curry",
    "Indian Curry",
  ],
  "Pizza": [
    "Cheese",
    "Pepperoni",
    "Deluxe",
    "Margherita",
    "Hawaiian",
    "Meat Lovers",
    "Veggie",
    "BBQ Chicken",
  ],
  "Fries": [
    "Regular",
    "Waffle",
    "Sweet Potato",
    "Curly",
    "Steak Fries",
    "Shoestring",
  ],
  "Churro": [
    "Plain",
    "Filled (Caramel)",
    "Filled (Chocolate)",
    "Cinnamon Sugar",
  ],
  "Cake": [
    "Chocolate",
    "Cheesecake",
    "Carrot Cake",
    "Red Velvet",
    "Vanilla",
    "Strawberry",
  ],
};

export const DIETARY_TAGS = [
  "Vegetarian",
  "Vegan",
  "Gluten-Free",
  "Dairy-Free",
  "Nut-Free",
  "Halal",
  "Kosher",
  "Spicy",
  "Low-Carb",
  "Keto-Friendly",
  "Sugar-Free",
  "Organic",
];

export const SIZE_OPTIONS = ["Small", "Medium", "Large", "Extra Large"];
